language: cpp
sudo: required

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  - gcc --version
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - cmake

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
    
#before_install:
# - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
# - sudo apt-get update -qq
# - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
# - sudo apt-get install qt5-default qttools5-dev-tools
 
install:
  - wget https://github.com/google/protobuf/releases/download/v3.4.0/protobuf-cpp-3.4.0.tar.gz
  - tar -xzvf protobuf-cpp-3.4.0.tar.gz
  - pushd protobuf-3.4.0 && ./configure --prefix=/usr && make && sudo make install && popd

script:
# - wget https://github.com/google/protobuf/releases/download/v3.4.0/protobuf-cpp-3.4.0.tar.gz
# - tar -xzvf protobuf-cpp-3.4.0.tar.gz
# - cd protobuf-3.4.0 && ./configure --prefix=/usr && make && sudo make install
# - sudo apt-get install libprotobuf-dev
# - sudo ldconfig
# - protoc --version
 - gcc --version
 - cd ../
 - mkdir _bld && cd _bld
 - cmake ../TemplateRepo/
 - make
 - make install
 