language: cpp
compiler: gcc
sudo: required

install:
  - wget https://github.com/google/protobuf/releases/download/v3.4.0/protobuf-cpp-3.4.0.tar.gz
  - tar -xzvf protobuf-cpp-3.4.0.tar.gz
  - pushd protobuf-3.4.0 && ./configure --prefix=/usr && make && sudo make install && popd
  - wget https://cmake.org/files/v3.10/cmake-3.10.0-rc3-Linux-x86_64.sh
  - sudo apt-get remove cmake
  - sudo chmod 777 cmake-3.10.0-rc3-Linux-x86_64.sh
  - ./cmake-3.10.0-rc3-Linux-x86_64.sh --skip-license --include-subdir
  - ./cmake-3.10.0-rc3-Linux-x86_64/bin/cmake --version
  - pwd
  - ls  
  - sudo apt-get install qt5-default libqt5core5a libqt5network5 qtcreator --yes
  
script:
 - cd ../
 - mkdir _bld && cd _bld
 - ./../TemplateRepo/cmake-3.10.0-rc3-Linux-x86_64/bin/cmake ../TemplateRepo/
 - make
 - make install
 - make test
 