language: cpp
compilers: gcc
sudo: required

before_install:
# - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
# - sudo apt-get update -qq
# - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
# - sudo apt-get install qt5-default qttools5-dev-tools
 
install:
  - wget https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz
  - tar -xzvf protobuf-cpp-3.0.0.tar.gz
  - pushd protobuf-3.0.0 && ./configure --prefix=/usr && make && sudo make install && popd

addons:
    apt:
        packages:
         - cmake

script:
# - wget https://github.com/google/protobuf/releases/download/v3.4.0/protobuf-cpp-3.4.0.tar.gz
# - tar -xzvf protobuf-cpp-3.4.0.tar.gz
# - cd protobuf-3.4.0 && ./configure --prefix=/usr && make && sudo make install
# - sudo apt-get install libprotobuf-dev
# - sudo ldconfig
# - protoc --version
 - cd ../
 - mkdir _bld && cd _bld
 - cmake ../TemplateRepo/
 - make
 - make install
 